# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - "[0-9]\\.[0-9]\\.[0-9]"

jobs:
  getVersion:
   if: github.event.base_ref == 'refs/heads/master'
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
     - run: echo $RELEASE_VERSION

  build:
    if: github.ref == 'refs/heads/main'
    needs: getVersion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm version $RELEASE_VERSION
      - run: npm install
      - run: npm run build
      #- run: npm test

  publish-npm:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
          
  release-github:
    if: github.ref == 'refs/heads/main'
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/"
        token: ${{ secrets.GITHUB_TOKEN }}
